### PR TITLE
Fixed fragment view crashing after stopping recording

### PR DESCRIPTION
**Pull request by madhavajay**
I have filled out an individual CLA under my github name.

This fixes the crashing issue found on this ticket:
https://github.com/googlesamples/android-Camera2Video/issues/2

Thanks to commit from pjcollins on xamarin monodroid
https://github.com/xamarin/monodroid-samples/commit/3bb7d67f1d12698a63d3ae16247a54a2c9c16e4e

### CODE REVIEW

**Comment by ahmedjafri** [comment]
Looks like setting the outputFile on the mediaRecorder clears the outputFile if it exists so while this seems to work in not crashing the app, the recorded file is not retained on disk. I worked around this by having two files and swapping them before calling openCamera().

**Comment by madhavajay** [comment]
Did this issue ever get resolved via a PR?

**Comment by RoundSparrow** [comment]
Did this get resolved?

**Comment by ivv19041994** [comment]
https://github.com/xamarin/monodroid-samples/commit/3bb7d67f1d12698a63d3ae16247a54a2c9c16e4e 
is not working correctly. 
When i am stoping record, i get many errors, but app dont crash.
CaptureSesion error come up, when Surface of MediaRecoder  is Destroy. 
Its easy fixed:
    private void setUpMediaRecorder() throws IOException {
        final Activity activity = getActivity();
        if (null == activity) {
            return;
        }
        mMediaRecorder.setAudioSource(MediaRecorder.AudioSource.MIC);
        mMediaRecorder.setVideoSource(MediaRecorder.VideoSource.SURFACE);
        mMediaRecorder.setOutputFormat(MediaRecorder.OutputFormat.MPEG_4);
        //if (mNextVideoAbsolutePath == null || mNextVideoAbsolutePath.isEmpty()) {
            mNextVideoAbsolutePath = getVideoFilePath(getActivity());
            Toast.makeText(activity, "Video will save: " + mNextVideoAbsolutePath,
                    Toast.LENGTH_SHORT).show();

        //}
        mMediaRecorder.setOutputFile(mNextVideoAbsolutePath);
        mMediaRecorder.setVideoEncodingBitRate(10000000);
        mMediaRecorder.setVideoFrameRate(30);
        mMediaRecorder.setVideoSize(mVideoSize.getWidth(), mVideoSize.getHeight());
        mMediaRecorder.setVideoEncoder(MediaRecorder.VideoEncoder.H264);
        mMediaRecorder.setAudioEncoder(MediaRecorder.AudioEncoder.AAC);
        int rotation = activity.getWindowManager().getDefaultDisplay().getRotation();
        switch (mSensorOrientation) {
            case SENSOR_ORIENTATION_DEFAULT_DEGREES:
                mMediaRecorder.setOrientationHint(DEFAULT_ORIENTATIONS.get(rotation));
                break;
            case SENSOR_ORIENTATION_INVERSE_DEGREES:
                mMediaRecorder.setOrientationHint(INVERSE_ORIENTATIONS.get(rotation));
                break;
        }
        mMediaRecorder.prepare();
    }

private void stopRecordingVideo() {
        // UI
        mIsRecordingVideo = false;
        mButtonVideo.setText(R.string.record);


        Activity activity = getActivity();
        if (null != activity) {
            Toast.makeText(activity, "Video saved: " + mNextVideoAbsolutePath,
                    Toast.LENGTH_SHORT).show();
        }
        try {
            closePreviewSession();
            startPreview();
        } catch (CameraAccessException e) {
            e.printStackTrace();
        }
        // Stop recording
        mMediaRecorder.stop();
        mMediaRecorder.reset();

    }

**Comment by codingjeremy** [comment]
This sample has been migrated to a new location (check README for more information). 

[As recommended by GitHub][1], we are closing all issues and pull requests now that this older repo will be archived. 

If you still see this issue in the updated repo, please reopen the issue/PR there. Thank you!

[1]: https://help.github.com/en/articles/archiving-repositories

**Pull request closed without merging**
